stages:
  - test
  - deploy

image: node:8

before_script:  
  - npm install

cache:  
  paths:
    - node_modules/

test:
  stage: test
  script:
    - npm run lint

publish:
  stage: deploy
  only:
    - tags
    - triggers
  script:
    - npm run build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish